# Generated by Django 3.1.13 on 2021-10-08 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('septic_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='user_sewer_info',
            new_name='user_septic_info',
        ),
        migrations.AlterField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
