# Generated by Django 3.1.13 on 2021-10-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('septic_api', '0002_auto_20211008_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='user_septic_info',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
