# Generated by Django 3.1.13 on 2021-10-08 17:03

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('septic_api', '0003_auto_20211008_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='home',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
    ]
